#!/usr/bin/env bun
/**
 * Emits src/tests.generated.ts with STATIC imports of every test module.
 *
 * Why this exists: `bun build --compile` bundles only statically-reachable
 * code, so the runtime `await import(dir)` registry works from source but the
 * compiled binary cannot resolve the tests or their dependencies. Generating
 * the imports keeps "adding a test = adding one file" true - the build
 * regenerates this; nobody edits it.
 *
 * Every experiment's tests go into ONE registry, and selection happens at run
 * time (`--only`, `--where`, capability gating). The alternative - naming one
 * experiment's dir at build time - made the binary carry whichever experiment
 * was built last, and any other experiment's tests were unreachable from it
 * entirely. Registering all of them costs nothing, because a test whose
 * project ref is absent self-skips with a reason.
 *
 *   bun scripts/gen-registry.ts                       # all experiments
 *   bun scripts/gen-registry.ts ../experiments/x/tests # explicit subset
 */
import { readdir } from "node:fs/promises";
import { relative, resolve } from "node:path";

const experimentsRoot = resolve(import.meta.dir, "../../experiments");

async function allTestDirs(): Promise<string[]> {
  const entries = await readdir(experimentsRoot, { withFileTypes: true });
  const dirs: string[] = [];
  for (const e of entries.filter((e) => e.isDirectory()).sort((a, b) => a.name.localeCompare(b.name, "en"))) {
    const candidate = resolve(experimentsRoot, e.name, "tests");
    try {
      await readdir(candidate);
      dirs.push(candidate);
    } catch {
      // an experiment with no tests dir is legitimate (infra-only)
    }
  }
  return dirs;
}

const argDirs = process.argv.slice(2).map((d) => resolve(d));
const dirs = argDirs.length ? argDirs : await allTestDirs();
const outFile = resolve(import.meta.dir, "../src/tests.generated.ts");

const found: { dir: string; file: string }[] = [];
for (const dir of dirs) {
  const files = (await readdir(dir)).filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts")).sort();
  for (const file of files) found.push({ dir, file });
}

const lines = [
  "// GENERATED by scripts/gen-registry.ts - do not edit.",
  ...dirs.map((d) => `// Source: ${relative(resolve(import.meta.dir, ".."), d)}`),
  'import type { TestModule } from "./types";',
];

found.forEach(({ dir, file }, i) => {
  const spec = relative(resolve(import.meta.dir, "../src"), resolve(dir, file)).replace(/\.ts$/, "");
  lines.push(`import m${i} from "${spec.startsWith(".") ? spec : `./${spec}`}";`);
});

lines.push("");
lines.push(`export const tests: TestModule[] = [${found.map((_, i) => `m${i}`).join(", ")}];`);
lines.push("");

await Bun.write(outFile, lines.join("\n"));
console.log(`generated ${found.length} test imports -> src/tests.generated.ts`);
for (const { dir, file } of found) console.log(`  ${relative(experimentsRoot, resolve(dir, file))}`);
