#!/usr/bin/env bun
/**
 * Emits src/tests.generated.ts with STATIC imports of every test module.
 *
 * Why this exists: `bun build --compile` bundles only statically-reachable
 * code, so the runtime `await import(dir)` registry works from source but the
 * compiled binary cannot resolve the tests or their dependencies. Generating
 * the imports keeps "adding a test = adding one file" true - the build
 * regenerates this; nobody edits it.
 *
 *   bun scripts/gen-registry.ts ../experiments/privatelink-aws/tests
 */
import { readdir } from "node:fs/promises";
import { relative, resolve } from "node:path";

const dir = resolve(process.argv[2] ?? "../experiments/privatelink-aws/tests");
const outFile = resolve(import.meta.dir, "../src/tests.generated.ts");

const files = (await readdir(dir))
  .filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts"))
  .sort();

const lines = [
  "// GENERATED by scripts/gen-registry.ts - do not edit.",
  `// Source: ${relative(resolve(import.meta.dir, ".."), dir)}`,
  'import type { TestModule } from "./types";',
];

files.forEach((f, i) => {
  const spec = relative(resolve(import.meta.dir, "../src"), resolve(dir, f)).replace(/\.ts$/, "");
  lines.push(`import m${i} from "${spec.startsWith(".") ? spec : `./${spec}`}";`);
});

lines.push("");
lines.push(`export const tests: TestModule[] = [${files.map((_, i) => `m${i}`).join(", ")}];`);
lines.push("");

await Bun.write(outFile, lines.join("\n"));
console.log(`generated ${files.length} test imports -> src/tests.generated.ts`);
for (const f of files) console.log(`  ${f}`);
